title: "Request to add a repository to rs-station"
labels: ["Repositories"]
body:
  - type: dropdown
    attributes: 
      label: Please select the appropriate repository track for your repo. 
      options: 
        - Development (beta) repo
        - Production repo
  - type: input
    attributes:
      label: Repository name
  - type: input
    attributes:
      label: Repository URL
  - type: input
    attributes:
      label: Repository authors and contributors
  - type: textarea
    attributes:
      label: Describe your project. What problem does it solve? What's the use case?
  - type: textarea
    attributes:
      label: Why does this project belong on the Reciprocal Space Station?
  - type: textarea
    attributes:
      label: What rs-station admin would you like to sponsor your repo? (use @username)
  - type: textarea
    attributes:
      label: More info. Anything else you'd like to tell us? Any citations, likes, or materials of interest?

